---
formatter: markdown table

header-from: main.tf
content: |-
    # ☁️ AWS RDS Proxy
    ## Description
    {{ .Header }}
    This module is used to create an AWS RDS Proxy. The current capabilities are supported:
    * 🚀 Create an AWS RDS Proxy
    * 🚀 Create an AWS RDS Proxy Target Group

    For more information about the RDS DB Proxy, please query: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_proxy

    ---
    ## Example
    Examples of this module's usage are available in the [examples](./examples) folder.

    ```hcl
    {{ include "../../examples/rds-db-proxy/basic/main.tf" }}
    ```

    For module composition, It's recommended to take a look at the module's `outputs` to understand what's available:
    ```hcl
    {{ include "outputs.tf" }}
    ```

    A basic implementation that includes default target group:
    ```hcl
    {{ include "../../examples/rds-db-proxy/basic/config/fixtures-with-default-target-group.tfvars" }}
    ```

    A basic implementation that includes timeouts:
    ```hcl
    {{ include "../../examples/rds-db-proxy/basic/config/fixtures-with-timeouts.tfvars" }}
    ```
    ---

    ## Module's documentation
    (This documentation is auto-generated using [terraform-docs](https://terraform-docs.io))
    {{ .Providers }}

    {{ .Modules }}

    {{ .Resources }}

    {{ .Requirements }}

    {{ .Inputs }}

    {{ .Outputs }}

output:
    file: README.md
    mode: inject
    template: |-
        <!-- BEGIN_TF_DOCS -->
        {{ .Content }}
        <!-- END_TF_DOCS -->
settings:
    anchor: true
    color: true
